network_params:
  input_channel: 1
  output_channel: 256
  hidden_size: 256
imgH: 300
#lang_list:
#         - 'en'
character_list: 0123456789!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~ €ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz

number: '0123456789'
symbol: "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ €"
lang_char: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'
workers: 1
batch_size: 32 #32
saved_model: '../finalSavedModels/wb_v2/wb_v2.pth' #'saved_models/en_filtered/iter_300000.pth'
batch_max_length: 34
imgH: 300
imgW: 300
rgb: False
sensitive: True
PAD: True
baiduCTC: True
Transformation: 'None'
FeatureExtraction: 'VGG'
SequenceModeling: 'BiLSTM'
Prediction: 'CTC'
num_fiducial: 20
input_channel: 1
output_channel: 256
hidden_size: 256
